# 使用特定版本的 Golang 镜像
FROM golang:1.20.11 as builder

# 设置工作目录
WORKDIR /app

# 复制你的单一 main.go 文件到工作目录
COPY code/main.go .

# 构建你的应用程序
RUN GO111MODULE=off CGO_ENABLED=0 GOOS=linux go build -o myapp

# 使用轻量级基础镜像运行
FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/myapp .
CMD ["./myapp"]
