FROM golang:1.20.11 as builder

WORKDIR /app

COPY app/main.go .

RUN go build -o /app/main .

# Path: worker/pkg/docker/dockerfile
FROM alpine:3.14.2

WORKDIR /app

COPY --from=builder /app/main .

CMD ["/app/main"]
