FROM golang:1.21.1 AS build

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o master ./cmd/master/main.go


FROM alpine:latest

WORKDIR /app

COPY --from=build /app/master /app/master

VOLUME /sandbox

RUN mkdir /app/dockerfile

EXPOSE 8080

CMD ["/app/master"]
