FROM golang:1.21.1 AS build

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker/main.go


FROM alpine:latest

WORKDIR /app
COPY --from=build /app/worker /app/worker

VOLUME /sandbox
RUN mkdir /app/dockerfile

EXPOSE 50051

CMD ["/app/worker"]
